# -*- coding: utf-8 -*-
"""module1review.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G28thxXk4-mAjbNBrYnFtf5-RgcN_y4U
"""

## Violation 1: Hardcoded API Key (Security Risk)

API_KEY = "free_tier_key_abc123"

## Corrected Version:

import os

API_KEY = os.getenv("API_KEY")

## Set environment variable:
export API_KEY="your_actual_key"

## Violation 2: Permanent Storage of Raw PII Data
save_to_database(records)

## Corrected Version:
def anonymize(record):
    return {
        "age_group": "20-30",   # example replacing DOB
        "region": record["zip_code"][:3],  # partial zip masking
        "job_category": record["job_title"],
        "diagnosis_notes": remove_identifiers(record["diagnosis_notes"])
    }

clean_records = [anonymize(r) for r in records]

save_to_database(clean_records)

## Additional Improved Script
import requests
import os

API_URL = "https://healthstats-api.example.com/records"
API_KEY = os.getenv("API_KEY")

records = []

for page in range(1,101):
    response = requests.get(
        API_URL,
        params={
            "page": page,
            "key": API_KEY
        }
    )

    data = response.json()

    for r in data["results"]:
        cleaned = {
            "age_group": "20-30",
            "region": r["zip_code"][:3],
            "job_category": r["job_title"]
        }

        records.append(cleaned)

save_to_database(records)